apiVersion: v1
kind: Secret
metadata:
  name: terway-controlplane-credential
  labels:
  {{- include "terway-controlplane.labels" . | nindent 4 }}
stringData:
  ctrl-secret.yaml: |
    accessKey: "{{ .Values.terwayControlplane.accessKey }}"
    accessSecret: "{{ .Values.terwayControlplane.accessSecret }}"
    credentialPath: "{{ .Values.terwayControlplane.credentialPath }}"
    otelEndpoint: "{{ .Values.terwayControlplane.otelEndpoint }}"
    otelToken: "{{ .Values.terwayControlplane.otelToken }}"

